name = "loooongly"
type = "webpack"

account_id = "6179c5dca2b24c8146211c0fda983e82"
workers_dev = true
route = ""
zone_id = "f0b0d63ae55d5e495047f4b5ab5b8996"
compatibility_date = "2022-01-22"
kv_namespaces = [ 
    { binding = "LONG_DEV", id = "fa125ef780ed47fea9fe2aeae5093e2c", preview_id = "fa125ef780ed47fea9fe2aeae5093e2c" }
]   